/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentacar;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import vista.arriendo.MenuArriendo;
import vista.vehiculo.MenuVehiculo;

/**
 *
 * @author fredy
 */
public class MenuPrincipal extends javax.swing.JFrame implements ActionListener,ItemListener {

    /**
     * Creates new form MenuPrincipal
     */
    JMenuBar menuBar;
    JMenu menuAdministrar,menuGestion;
    JMenuItem menuItemVehiculos;
    JMenuItem menuItemMantenciones;
    JMenuItem menuItemClientes;
    JMenuItem menuItemArriendos;
    JMenuItem menuItemCobranzas;
    
    public MenuPrincipal() {
        initComponents();
        construirMenu();
    }
     private void construirMenu() {
         //Instanciamos variables de objeto globales
         menuBar                = new JMenuBar();
         menuAdministrar        = new JMenu("Administración");
         menuGestion            = new JMenu("Gestión");
         menuItemVehiculos      = new JMenuItem("Vehículos");
         menuItemMantenciones   = new JMenuItem("Mantenciones");
         menuItemClientes       = new JMenuItem("Clientes");
         menuItemArriendos      = new JMenuItem("Arriendos");
         menuItemCobranzas      = new JMenuItem("Cobranzas");
         //Asociamos los objetos según corresponda
         //Asociamos menu a menubar y los item de cada menú.
         menuBar.add(menuAdministrar);
         menuBar.add(menuGestion);
         
         menuAdministrar.add(menuItemVehiculos);
         menuAdministrar.add(menuItemMantenciones);
         menuAdministrar.add(menuItemCobranzas);
         
         menuGestion.add(menuItemClientes);
         menuGestion.add(menuItemArriendos);
         //Habilitamos listener para los elementos del menú
         menuItemVehiculos.addActionListener(this);
         menuItemArriendos.addActionListener(this);
         
         //Habilitamos el menubar a este JFrame
         this.setJMenuBar(menuBar);
     
         
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sistema de Gestión RentACar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel1)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        //EValuamos que elemento fué seleccionado y ejecutamos una acción
        if(e.getSource() == menuItemVehiculos){
            //Desplegamos el JFrame de administración de vehículos
            MenuVehiculo menuVehiculo = new MenuVehiculo();
            menuVehiculo.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            menuVehiculo.setVisible(true);
        }
        if(e.getSource() == menuItemArriendos){
            //Desplegamos el JFrame de administración de vehículos
            MenuArriendo menuArriendo = new MenuArriendo();
            menuArriendo.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            menuArriendo.setVisible(true);
        }
        
    }

    @Override
    public void itemStateChanged(ItemEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   
}
