/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.vehiculo;


import java.util.HashMap;
import modelo.ListaGenerica;
import modelo.Vehiculo;

/**
 *
 * @author fredy
 */
public class AgregarVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form AgregarVehiculo
     */
    public AgregarVehiculo() {
        initComponents();
        completarComboBoxMarcas();
        completarComboBoxTipoVehiculo();
        completarComboBoxTipoCarroceria();
        completarComboBoxColorVehiculo();
        completarComboBoxEstadoVehiculo();
    }
        private void completarComboBoxColorVehiculo() {
        //Instsnciamos la clase ListaGenerica
        ListaGenerica listaGenerica = new ListaGenerica();
        //Creamos hashmap local para almacenar valores
        HashMap<String, Integer> hashMapColores = listaGenerica.generarValoresColores();
  
        for(String s : hashMapColores.keySet()){
            //Agregamos valores a combobox
           cmb_color.addItem(s);
        }
    }
            private void completarComboBoxMarcas() {
        //Instsnciamos la clase ListaGenerica
        ListaGenerica listaGenerica = new ListaGenerica();
        //Creamos hashmap local para almacenar valores
        HashMap<String, Integer> hashMapMarcas = listaGenerica.generarValoresMarca();
        //EFectuamos un recorrido para agregar valores a combobox de marcas
        for(String s : hashMapMarcas.keySet()){
            //Agregamos valores a combobox
           cmb_marcas.addItem(s);
        }
    }
    private void completarComboBoxEstadoVehiculo() {
        //Instsnciamos la clase ListaGenerica
        ListaGenerica listaGenerica = new ListaGenerica();
        //Creamos hashmap local para almacenar valores
        HashMap<String, Integer> hashMapEstadoVehiculo = listaGenerica.generarValoresEstadoVehiculo();

        for(String s : hashMapEstadoVehiculo.keySet()){
            //Agregamos valores a combobox
           cmb_estado_vehiculo.addItem(s);
        }
    }
        private void completarComboBoxTipoVehiculo() {
        //Instsnciamos la clase ListaGenerica
        ListaGenerica listaGenerica = new ListaGenerica();
        //Creamos hashmap local para almacenar valores
        HashMap<String, Integer> hashMapTipoVehiculo = listaGenerica.generarValoresTipoVehiculo();
        //EFectuamos un recorrido para agregar valores a combobox de marcas
        for(String s : hashMapTipoVehiculo.keySet()){
            //Agregamos valores a combobox
           cmb_tipo_vehiculo.addItem(s);
        }
    }
                private void completarComboBoxTipoCarroceria() {
        //Instsnciamos la clase ListaGenerica
        ListaGenerica listaGenerica = new ListaGenerica();
        //Creamos hashmap local para almacenar valores
        HashMap<String, Integer> hashMapTipoCarroceria= listaGenerica.generarValoresTipoCarroceria();
        //EFectuamos un recorrido para agregar valores a combobox de marcas
        for(String s : hashMapTipoCarroceria.keySet()){
            //Agregamos valores a combobox
           cmb_tipo_carroceria.addItem(s);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cmb_marcas = new javax.swing.JComboBox<>();
        cmb_tipo_vehiculo = new javax.swing.JComboBox<>();
        cmb_tipo_carroceria = new javax.swing.JComboBox<>();
        txt_modelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_año = new javax.swing.JTextField();
        txt_cilindrada = new javax.swing.JTextField();
        txt_patente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmb_color = new javax.swing.JComboBox<>();
        cmb_estado_vehiculo = new javax.swing.JComboBox<>();
        txt_valor_arriendo = new javax.swing.JTextField();
        txt_kilometraje_actual = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_agregar_vehiculo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Agregar Vehiculo");

        jLabel2.setText("Marca");

        jLabel3.setText("Tipo de Vehiculo");

        jLabel4.setText("Tipo de Carrocería");

        jLabel5.setText("Modelo");

        txt_cilindrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cilindradaActionPerformed(evt);
            }
        });

        jLabel6.setText("Año");

        jLabel7.setText("Cilindrada");

        jLabel8.setText("Patente");

        jLabel9.setText("Color");

        jLabel10.setText("Estado Vehiculo");

        jLabel11.setText("Valor Arriendo");

        jLabel12.setText("Kilometraje Actual");

        btn_agregar_vehiculo.setBackground(new java.awt.Color(153, 255, 153));
        btn_agregar_vehiculo.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btn_agregar_vehiculo.setForeground(new java.awt.Color(51, 51, 51));
        btn_agregar_vehiculo.setText("Agregar Vehículo");
        btn_agregar_vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_vehiculoActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmb_tipo_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(184, 184, 184)
                                .addComponent(cmb_marcas, 0, 169, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmb_tipo_carroceria, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_agregar_vehiculo))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_patente, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_año, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_cilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_color, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_estado_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_valor_arriendo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_kilometraje_actual, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(6, 6, 6))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_marcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_tipo_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_tipo_carroceria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_patente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_estado_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_valor_arriendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kilometraje_actual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar_vehiculo)
                    .addComponent(jButton2))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cilindradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cilindradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cilindradaActionPerformed

    private void btn_agregar_vehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_vehiculoActionPerformed
        //Creamos un objeto de la clase Vehiculo
        Vehiculo vehiculo = new Vehiculo();
        //Asignamos valores a  propiedades el objeto vehiculo
        /*Marca*/
        ListaGenerica listaGenericaMarca = new ListaGenerica();
        HashMap<String, Integer> mapMarca = listaGenericaMarca.generarValoresMarca();
        int idMarca = Integer.parseInt(mapMarca.get(cmb_marcas.getSelectedItem().toString()).toString());
        vehiculo.setMarca(idMarca);
      
        /*Tipo de vehículo*/
        ListaGenerica listaGenericaTipoVehiculo = new ListaGenerica();
        HashMap<String, Integer> mapTipoVehiculo = listaGenericaTipoVehiculo.generarValoresTipoVehiculo();
        int idTipoVehiculo = Integer.parseInt(mapTipoVehiculo.get(cmb_tipo_vehiculo.getSelectedItem().toString()).toString());
        vehiculo.setTipoVehiculo(idTipoVehiculo);
        
        /*Tipo de vehículo*/
        ListaGenerica listaGenericaTipoCarroceria = new ListaGenerica();
        HashMap<String, Integer> mapTipoCarroceria = listaGenericaTipoCarroceria.generarValoresTipoCarroceria();
        int idTipoCarroceria = Integer.parseInt(mapTipoCarroceria.get(cmb_tipo_carroceria.getSelectedItem().toString()).toString());
        vehiculo.setTipoCarroceria(idTipoCarroceria);
        
        vehiculo.setModelo(txt_modelo.getText());
        vehiculo.setAno(Integer.parseInt(txt_año.getText()));
        vehiculo.setCilindrada(Integer.parseInt(txt_cilindrada.getText()));
        vehiculo.setPatente(txt_patente.getText());
        
         /*color*/
        ListaGenerica listaGenericaColor= new ListaGenerica();
        HashMap<String, Integer> mapColor = listaGenericaColor.generarValoresColores();
        int idColor = Integer.parseInt(mapColor.get(cmb_color.getSelectedItem().toString()).toString());
        vehiculo.setColor(idColor);
        
        /*estado de vehículo*/
        ListaGenerica listaGenericaEstadoVehiculo = new ListaGenerica();
        HashMap<String, Integer> mapEstadoVehiculo = listaGenericaEstadoVehiculo.generarValoresEstadoVehiculo();
        int idEstadoVehiculo = Integer.parseInt(mapEstadoVehiculo.get(cmb_estado_vehiculo.getSelectedItem().toString()).toString());
        vehiculo.setEstadoVehiculo(idEstadoVehiculo);
        
        vehiculo.setValorArriendo(Double.parseDouble(txt_valor_arriendo.getText()));
        vehiculo.setKilometrajeActual(Integer.parseInt(txt_kilometraje_actual.getText()));
        vehiculo.setUsuarioRegistro(11200300);
      
        //Invocamos método para agregar vehiculo
        vehiculo.agregarVehiculo();
        
        
        
    }//GEN-LAST:event_btn_agregar_vehiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar_vehiculo;
    private javax.swing.JComboBox<String> cmb_color;
    private javax.swing.JComboBox<String> cmb_estado_vehiculo;
    private javax.swing.JComboBox<String> cmb_marcas;
    private javax.swing.JComboBox<String> cmb_tipo_carroceria;
    private javax.swing.JComboBox<String> cmb_tipo_vehiculo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txt_año;
    private javax.swing.JTextField txt_cilindrada;
    private javax.swing.JTextField txt_kilometraje_actual;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_patente;
    private javax.swing.JTextField txt_valor_arriendo;
    // End of variables declaration//GEN-END:variables


}
